
safe: false

markdown: kramdown
highlighter: false

exclude: [
  "README.md",
  "LICENSE.md",
  "CNAME",
  ".gitignore",
  "scripts",
  "debug",
  "Allopoeia.sublime-project",
  "Allopoeia.sublime-workspace"
]

## Site configuration

url: http://allopoeia.komiga.com
meta:
  perma-url: http://allopoeia.komiga.com
  title: Allopoeia
  run-years: "2012-2014"
  image: http://lh4.googleusercontent.com/-0cni5iXgy_8/Uf7NKDyANjI/AAAAAAAAALo/ZHUIsfHxxVc/k-inv-256.png
  feedburner_id: Allopoeia
  flattr_slug: "/thing/493250/Allopoeia"
  disqus_shortname: komiga
  analytics_id: "UA-6565507-3"
  analytics_domain_name: null

## Style

style:
  format:
    ymd: '%d %B %Y'

permalink: /:categories/:year/:month/:title.html

## Static content

nav-items: {
  root: {
    text: "Allopoeia",
    url : "/"
  },
  archive: {
    text: "Archive",
    url : "/archive.html"
  },
  authors: {
    text: "Authors",
    url : "/authors.html"
  },
  authoring: {
    text: "Authoring",
    url : "/authoring.html"
  },
  about: {
    text: "About",
    url : "/about.html"
  }
}

personal-site-types: {
  website: {
    class: home,
    text : "Web site",
    title: "Web site",
    base-url: "http://"
  },
  flattr : {
    class: flattr,
    text : "Flattr",
    title: "Flattr",
    base-url: "http://flattr.com/profile/"
  },
  twitter: {
    class: twitter,
    text : "Twitter",
    title: "Twitter",
    base-url: "http://twitter.com/"
  },
  github : {
    class: github ,
    text : "GitHub",
    title: "GitHub",
    base-url: "https://github.com/"
  }
}

authors: {
  "plash": {
    about-url: "/authors.html#plash",
    about-relative: true,
    preferred-copyright: "cc_by-nc-sa-3.0",
    personal-sites: [
      {type: website, slug: "komiga.com"},
      {type: flattr , slug: "komiga"},
      {type: github , slug: "komiga"},
      {type: twitter, slug: "komiga"}
    ]
  }
}

##
## Replacement fields:
##    %about-author% - the author's about-url
##    %year-range% - the post's modification years
##    %author% - the author's moniker
##
copyright-notice-type-default: "preferred"
copyright-notices: {
  "simple": {
    url: "%about-author%",
    pre-text: "&copy; %year-range% ",
    url-text: "%author%",
    post-text: ""
  },
  "cc_by-nc-sa-3.0": {
    url: "http://creativecommons.org/licenses/by-nc-sa/3.0/",
    pre-text: "&copy; %year-range% %author%, under license ",
    url-text: "Creative Commons BY-NC-SA 3.0",
    post-text: ""
  }
}
